version: '3.8'

services:
  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-nest-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER:-your-email@gmail.com}
      - EMAIL_PASS=${EMAIL_PASS:-your-email-password}
    networks:
      - auth-network
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
      "

  # Development version (optional)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth-nest-app-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER:-your-email@gmail.com}
      - EMAIL_PASS=${EMAIL_PASS:-your-email-password}
    networks:
      - auth-network
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
    command: npm run start:dev

volumes:
  mysql_data:

networks:
  auth-network:
    driver: bridge 